FROM debian:stretch

LABEL maintainer="{{author_name}} <{{author_email}}>"
LABEL description="{{description}}"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq
RUN apt-get dist-upgrade -y
RUN apt-get install -y libncurses5 \
                       libssl1.0 \
                       libexpat1 \
                       libgpm2
RUN apt-get clean

WORKDIR /opt
ADD _build/prod/rel/{{name}} /opt/{{name}}
WORKDIR /opt/{{name}}

ENTRYPOINT ["/opt/{{name}}/bin/start-prod.sh", "console"]
